# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 561, 371))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CaesarCipher = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.CaesarCipher.setFont(font)
        self.CaesarCipher.setAlignment(QtCore.Qt.AlignCenter)
        self.CaesarCipher.setObjectName("CaesarCipher")
        self.verticalLayout.addWidget(self.CaesarCipher)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.plain = QtWidgets.QLabel(self.widget)
        self.plain.setObjectName("plain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plain)
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_plain_text)
        self.key = QtWidgets.QLabel(self.widget)
        self.key.setObjectName("key")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.key)
        self.txt_key = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_key.setObjectName("txt_key")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_key)
        self.Cipher = QtWidgets.QLabel(self.widget)
        self.Cipher.setObjectName("Cipher")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Cipher)
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.widget)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_cipher_text)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_encrypt = QtWidgets.QPushButton(self.widget)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.horizontalLayout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.widget)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.horizontalLayout.addWidget(self.btn_decrypt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CaesarCipher.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.plain.setText(_translate("MainWindow", "Plain text:"))
        self.key.setText(_translate("MainWindow", "Key:"))
        self.Cipher.setText(_translate("MainWindow", "Ciphertext:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
